replicaCount: 5

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30303

resources:
  requests:
    memory: "1024Mi"
    cpu: "100m"
  limits:
    memory: "1024Mi"
    cpu: "200m"
