apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metrics-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-metrics-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-metrics-app
    spec:
      containers:
        - name: metrics-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metrics-app-secret
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          
          # resources:
          #   requests:
          #     memory: "1024Mi"
          #     cpu: "100m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "200m"
