apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics-app
spec:
  selector:
    app: {{ .Release.Name }}-metrics-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
